/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/farms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Farm
         * @description Persist an officer-drawn farm boundary. Geometry validity,
         *     closedness, coordinate range, and non-zero area are already enforced
         *     by FarmCreateRequest at the request-parsing boundary (app/schemas/farm.py).
         */
        post: operations["create_farm_api_v1_farms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/farms/{farm_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Farm */
        get: operations["get_farm_api_v1_farms__farm_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/farms/{farm_id}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Report */
        post: operations["trigger_report_api_v1_farms__farm_id__reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{risk_score_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_api_v1_reports__risk_score_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** FactorScoreResponse */
        FactorScoreResponse: {
            factor: components["schemas"]["RiskFactor"];
            /** Value */
            value: number;
            band: components["schemas"]["RiskBand"];
            /** Raw Inputs */
            raw_inputs: {
                [key: string]: unknown;
            };
        };
        /** FarmCreateRequest */
        FarmCreateRequest: {
            /**
             * Village Id
             * Format: uuid
             */
            village_id: string;
            geometry: components["schemas"]["GeoJSONPolygon"];
        };
        /** FarmResponse */
        FarmResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Village Id
             * Format: uuid
             */
            village_id: string;
            /** Area Ha */
            area_ha: number;
            /**
             * Drawn By
             * Format: uuid
             */
            drawn_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * GeoJSONPolygon
         * @description A single-ring GeoJSON Polygon (no holes, no MultiPolygon) — a
         *     hand-drawn farm boundary is expected to be one simple, contiguous
         *     shape (Blueprint §01: manual polygon drawing is the deliberate MVP
         *     approach).
         */
        GeoJSONPolygon: {
            /**
             * Type
             * @constant
             */
            type: "Polygon";
            /** Coordinates */
            coordinates: [
                number,
                number
            ][][];
            /** Crs */
            crs?: {
                [key: string]: unknown;
            } | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "pending" | "running" | "done" | "failed";
        /** JobStatusResponse */
        JobStatusResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            type: components["schemas"]["JobType"];
            status: components["schemas"]["JobStatus"];
            /** Entity Id */
            entity_id: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * JobType
         * @enum {string}
         */
        JobType: "farm_report" | "portfolio_aggregation";
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            role: components["schemas"]["UserRole"];
            /** Expires In */
            expires_in: number;
            /** Full Name */
            full_name: string;
        };
        /** ReportGenerateRequest */
        ReportGenerateRequest: {
            /**
             * Lookback Years
             * @default 3
             */
            lookback_years: number;
        };
        /** ReportResponse */
        ReportResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Farm Id
             * Format: uuid
             */
            farm_id: string;
            /** Farm Area Ha */
            farm_area_ha: number;
            /**
             * Village Id
             * Format: uuid
             */
            village_id: string;
            /** Overall Score */
            overall_score: number;
            overall_band: components["schemas"]["RiskBand"];
            /** Confidence */
            confidence: number;
            /** Model Version */
            model_version: string;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Factors */
            factors: components["schemas"]["FactorScoreResponse"][];
        };
        /** ReportTriggerResponse */
        ReportTriggerResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Status
             * @default queued
             */
            status: string;
        };
        /**
         * RiskBand
         * @enum {string}
         */
        RiskBand: "low" | "moderate" | "high" | "very_high";
        /**
         * RiskFactor
         * @enum {string}
         */
        RiskFactor: "vegetation_stability" | "water_availability" | "drought_risk" | "flood_exposure";
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "credit_officer" | "branch_manager" | "risk_officer" | "ceo" | "chairman";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_farm_api_v1_farms_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FarmCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_farm_api_v1_farms__farm_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_report_api_v1_farms__farm_id__reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportTriggerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_v1_reports__risk_score_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                risk_score_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
