/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Sliding-session refresh (Product Design v2 B6): a caller holding a
         *     still-valid bearer token exchanges it for a fresh one with a full new
         *     expiry window, so an officer actively working doesn't get logged out
         *     mid-assessment purely because the 12h JWT clock ran out. `get_current_user`
         *     already re-validates the token and re-checks the user is active — this
         *     endpoint adds nothing beyond issuing a new token for the same identity,
         *     identical role-check-free shape as login's response.
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/villages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Villages */
        get: operations["search_villages_api_v1_villages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/farms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Farms
         * @description The Farms workspace index (M2B P7 — Product Design v2 §7, screen 7):
         *     every farm the caller owns or shares a branch with, each carrying its
         *     latest assessment (if any) and its currently in-flight run (if any) so
         *     the list alone answers "what's the state of every farm I map." Two
         *     small batch queries instead of a join, matching this codebase's
         *     existing style (no window functions) and MVP-pilot data volume.
         */
        get: operations["list_farms_api_v1_farms_get"];
        put?: never;
        /**
         * Create Farm
         * @description Persist an officer-drawn farm boundary. Geometry validity,
         *     closedness, coordinate range, and non-zero area are already enforced
         *     by FarmCreateRequest at the request-parsing boundary (app/schemas/farm.py).
         */
        post: operations["create_farm_api_v1_farms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/farms/{farm_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Farm */
        get: operations["get_farm_api_v1_farms__farm_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/farms/{farm_id}/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Farm Assessment History
         * @description Every completed assessment for this farm, newest first, plus the
         *     in-flight run if any — the Farm detail timeline (Product Design v2
         *     §7.4). Same append-only RiskScore history the risk engine already
         *     guarantees (Blueprint §04/§07); this endpoint is a read-model over it,
         *     nothing new persisted.
         */
        get: operations["get_farm_assessment_history_api_v1_farms__farm_id__assessments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Assessments
         * @description The Assessments workspace index (M2B P7 — Product Design v2 §7,
         *     screen 5): every farm_report run the caller owns or shares a branch
         *     with, farm context resolved regardless of run status.
         *
         *     `entity_id` is polymorphic by design (P4 decision, report_generator.py):
         *     while a job is in flight or failed it holds the farm_id it was
         *     triggered for; once DONE it is overwritten with the resulting
         *     risk_score_id. Listing "every assessment with its farm" therefore means
         *     resolving both shapes and merging them — no schema change, just reading
         *     what's already there two different ways.
         */
        get: operations["list_assessments_api_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/farms/{farm_id}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Report */
        post: operations["trigger_report_api_v1_farms__farm_id__reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{risk_score_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_api_v1_reports__risk_score_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reports
         * @description The Reports workspace index (M2B P7 — Product Design v2 §7, screen
         *     9): every issued report the caller owns or shares a branch with,
         *     newest first — the auditor/manager entry point ("show me every report
         *     issued," not "show me every farm"). One joined query; RiskScore is
         *     append-only so this is simply every farm-scored row in scope, no
         *     latest-per-farm collapsing (that collapsing is what the Farms index is
         *     for — this index is intentionally the full issued-artifact ledger).
         */
        get: operations["list_reports_api_v1_reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{risk_score_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report Pdf
         * @description Blueprint §API: rendered PDF, cached after first render. A risk
         *     score row is immutable once computed, so the cache is keyed on
         *     (risk_score_id, layout version) and never expires — a layout change
         *     bumps PDF_LAYOUT_VERSION rather than invalidating files.
         */
        get: operations["get_report_pdf_api_v1_reports__risk_score_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catchments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Catchments
         * @description Every catchment the caller created, newest first. Scoped by
         *     `created_by` (see module docstring for why, not organization
         *     membership) — a query that is IDOR-safe by construction: the WHERE
         *     clause itself excludes every other user's catchments, so there is no
         *     separate check to forget.
         *
         *     Pagination via `limit`/`offset` query params (default 50, capped at
         *     200 — "keep queries efficient" means bounding page size, not just
         *     indexing); total count is returned as the `X-Total-Count` response
         *     header rather than a wrapper response body, so this endpoint's
         *     response can stay a plain `list[CatchmentResponse]` without adding a
         *     new schema type (`Do NOT: Modify schemas`).
         */
        get: operations["list_catchments_api_v1_catchments_get"];
        put?: never;
        /**
         * Create Catchment
         * @description Persist a manually-drawn catchment boundary. Geometry validity,
         *     closedness, coordinate range, hole structure, and total vertex count
         *     are already enforced by `CatchmentCreateRequest` at the
         *     request-parsing boundary (`app/schemas/catchment.py`, M4-001).
         */
        post: operations["create_catchment_api_v1_catchments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catchments/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Catchment
         * @description Persist a catchment boundary from an uploaded GeoJSON, KML, or
         *     zipped-Shapefile file (`boundary_parser.py`, M4-002) — everything
         *     after the file is parsed into a `GeoJSONMultiPolygon` is identical to
         *     `create_catchment()` above, via the shared `_persist_catchment()`.
         *
         *     `name`/`organization_id`/`admin_boundary_id` arrive as multipart form
         *     fields (not a JSON body — this is a file upload), but are still
         *     validated through `CatchmentUploadRequest` (M4-001) before use, the
         *     same schema-level length/type checks `create_catchment()` gets for
         *     free from `CatchmentCreateRequest` — not re-implemented here.
         */
        post: operations["upload_catchment_api_v1_catchments_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catchments/{catchment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Catchment
         * @description A single catchment by id — 404 for both "doesn't exist" and
         *     "exists but isn't yours", the same `app/api/farms.py::get_farm`
         *     IDOR-safe convention: a resource outside the caller's scope must be
         *     indistinguishable from one that was never created at all, never
         *     revealed via a 403 that would confirm the id is real.
         *
         *     Returns the analysed geometry alongside the metadata (the list
         *     endpoint deliberately does not — see `CatchmentDetailResponse`), so a
         *     report can draw the exact area it was computed over rather than
         *     approximating it with the village boundary.
         */
        get: operations["get_catchment_api_v1_catchments__catchment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catchments/{catchment_id}/water-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Latest Water Report
         * @description The latest completed water report for a catchment — see the
         *     module docstring for the full "latest DONE job == latest computed_at
         *     result pair" correlation rationale. 404, not an empty/partial
         *     response, whenever no completed report exists yet (never triggered,
         *     still in flight, or every run so far has failed) or the catchment
         *     itself is outside the caller's own scope — the same IDOR-safe,
         *     not-found-vs-forbidden convention `get_catchment` already uses.
         */
        get: operations["get_latest_water_report_api_v1_catchments__catchment_id__water_reports_get"];
        put?: never;
        /**
         * Trigger Water Report
         * @description Create a water-report job for a catchment and schedule its
         *     background run — job creation only, per this ticket's scope (see the
         *     module docstring). Mirrors `app/api/reports.py::trigger_report`
         *     field-for-field: same IDOR-safe ownership check, same
         *     advisory-lock-guarded duplicate-in-flight-job check, same
         *     Job-then-BackgroundTasks split, same `ReportTriggerResponse` shape
         *     (reused as-is, not a new schema — `Do NOT: Modify schemas`).
         */
        post: operations["trigger_water_report_api_v1_catchments__catchment_id__water_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catchments/{catchment_id}/water-reports/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Water Report History
         * @description Every past completed run for a catchment, most recent first — not
         *     just the latest one `GET /catchments/{id}/water-reports` returns.
         *
         *     `WaterBalanceResult` and `RechargeStressScore` are both append-only
         *     (see their own model docstrings) — every trigger writes new rows,
         *     nothing is ever overwritten. This endpoint is the first thing that
         *     reads more than the single latest pair (docs/WELL_Labs_Raichur_Founder_Review_2026.md
         *     Part 2/5) — no new data, no schema change, purely additive.
         *
         *     Paired by an exact `computed_at` match, not by ordering-and-zipping
         *     two separately-limited lists: `water_report_generator.py` computes
         *     one `computed_at` per run and stamps both sibling rows with it
         *     (`WaterReportDetailResponse`'s own docstring), so an equality join on
         *     `(catchment_id, computed_at)` is the true correlation key. Zipping by
         *     position would silently mispair rows the moment the two tables ever
         *     drift out of lockstep (e.g. a future partial-failure path that
         *     persists one row without the other) — this join can't.
         */
        get: operations["get_water_report_history_api_v1_catchments__catchment_id__water_reports_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin-boundaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Admin Boundaries */
        get: operations["list_admin_boundaries_api_v1_admin_boundaries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin-boundaries/{boundary_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Admin Boundary */
        get: operations["get_admin_boundary_api_v1_admin_boundaries__boundary_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Ready
         * @description Deployment readiness probe (M3) — distinct from /health, which is a
         *     cheap liveness check with no dependencies and stays unchanged (asserted
         *     verbatim by tests/test_health.py). This one actually verifies the
         *     things a fresh deployment can get wrong: DB connectivity, and whether
         *     Earth Engine credentials are configured.
         *
         *     Earth Engine's check is deliberately config/credential-file presence,
         *     not a live ee.Initialize() call — actually initializing here would mean
         *     a real network round-trip (and, per GeeProvider's own design, a
         *     thread-pool hop — see docs/DECISIONS.md) on every orchestrator probe
         *     hit, which is impractical to do on a health-check cadence, not just
         *     undesirable. Container/compose healthchecks target the cheap /health,
         *     not this endpoint, for the same reason.
         */
        get: operations["health_ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveJobSummary */
        ActiveJobSummary: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            status: components["schemas"]["JobStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * AdminBoundaryDetail
         * @description Full detail for the Select Area preview/confirm step: the boundary's
         *     own geometry plus its resolved ancestor names at every level that
         *     applies (a taluka has no `village`; a village has all four).
         *
         *     `parent_id` is a direct passthrough of the existing column, added so
         *     a caller that already has one boundary's detail (a village, say) can
         *     fetch its immediate parent's own geometry and children — its taluka
         *     outline, and that taluka's other villages — without a second
         *     name-based lookup walking the hierarchy from the top.
         */
        AdminBoundaryDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            level: components["schemas"]["BoundaryLevel"];
            /** Name */
            name: string;
            /** Lgd Code */
            lgd_code: string | null;
            /** Parent Id */
            parent_id: string | null;
            /** State */
            state: string | null;
            /** District */
            district: string | null;
            /** Taluka */
            taluka: string | null;
            /** Village */
            village: string | null;
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
            /** Area Ha */
            area_ha: number;
        };
        /**
         * AdminBoundarySummary
         * @description One row in a cascading dropdown — deliberately minimal by default.
         *
         *     `geometry` stays `None` unless the caller explicitly asks for it with
         *     `?include_geometry=true`, so the dropdown case this schema was built
         *     for is byte-for-byte unchanged. The opt-in exists because drawing a
         *     village's neighbours is otherwise impossible without one request per
         *     neighbour: the per-id detail endpoint is the only other source of
         *     geometry, and a taluka like Devadurga has 185 villages. One request
         *     returning ~120 kB of simplified geometry replaces 185 round trips.
         */
        AdminBoundarySummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            level: components["schemas"]["BoundaryLevel"];
            /** Name */
            name: string;
            /** Lgd Code */
            lgd_code: string | null;
            /** Geometry */
            geometry?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * AssessmentListItem
         * @description One farm-report run with its farm context resolved. Farm fields are
         *     nullable because a completed job's entity_id was overwritten with the
         *     risk-score id (P4 decision) — if that score's farm were ever deleted,
         *     the run row must still list rather than crash the index.
         */
        AssessmentListItem: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            status: components["schemas"]["JobStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Farm Id */
            farm_id: string | null;
            /** Village Name */
            village_name: string | null;
            /** Area Ha */
            area_ha: number | null;
            /** Officer Name */
            officer_name: string;
            /** Risk Score Id */
            risk_score_id: string | null;
            /** Overall Score */
            overall_score: number | null;
            overall_band: components["schemas"]["RiskBand"] | null;
            /** Error Message */
            error_message: string | null;
        };
        /** AssessmentListResponse */
        AssessmentListResponse: {
            /** Items */
            items: components["schemas"]["AssessmentListItem"][];
            /** Total */
            total: number;
        };
        /**
         * AssessmentSummary
         * @description The latest completed assessment for a farm — enough for a list row;
         *     the full report stays behind GET /reports/{id}.
         */
        AssessmentSummary: {
            /**
             * Risk Score Id
             * Format: uuid
             */
            risk_score_id: string;
            /** Overall Score */
            overall_score: number;
            overall_band: components["schemas"]["RiskBand"];
            /** Confidence */
            confidence: number;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Model Version */
            model_version: string;
        };
        /**
         * BaselineWindow
         * @description Which historical window a recharge-stress or storage-change figure
         *     was benchmarked against (Blueprint v2 Part 4). Recharge-stress scoring
         *     uses CLIMATOLOGY_30YR, not TRAILING_3YR — a deliberate v2 fix: a short
         *     trailing window can silently redefine "normal" as "already stressed" if
         *     the recent years happen to be a drought sequence.
         * @enum {string}
         */
        BaselineWindow: "climatology_30yr" | "trailing_3yr";
        /** Body_upload_catchment_api_v1_catchments_upload_post */
        Body_upload_catchment_api_v1_catchments_upload_post: {
            /** File */
            file: string;
            /** Name */
            name: string;
            /** Organization Id */
            organization_id?: string | null;
            /** Admin Boundary Id */
            admin_boundary_id?: string | null;
        };
        /**
         * BoundaryLevel
         * @enum {string}
         */
        BoundaryLevel: "state" | "district" | "taluka" | "village";
        /**
         * CalibrationStatus
         * @description Whether a water_balance_result has ever been checked against real
         *     field data (Blueprint v2 D5) — deliberately separate from the
         *     data_completeness confidence score, which measures satellite data
         *     quality, not calibration. Defaults to UNCALIBRATED in MVP for every
         *     generic customer; see Blueprint v2 Risk Register #7.
         * @enum {string}
         */
        CalibrationStatus: "uncalibrated" | "partially_calibrated" | "field_calibrated";
        /**
         * CatchmentCreateRequest
         * @description `POST /catchments` request body (manual-draw path, a later
         *     ticket). `delineation_method` is deliberately NOT a client-supplied
         *     field on either request schema in this file — it is determined by
         *     which endpoint received the request (this one always means MANUAL;
         *     the upload endpoint always means UPLOAD), the same "one validation
         *     boundary, two ways in" design Blueprint v2 D2 already establishes,
         *     not a value the client should be trusted to assert.
         */
        CatchmentCreateRequest: {
            /** Name */
            name: string;
            geometry: components["schemas"]["GeoJSONMultiPolygon"];
            /**
             * Organization Id
             * @description Nullable in MVP — schema-ready for multi-tenancy, not yet enforced (Blueprint v2 D8).
             */
            organization_id?: string | null;
            /**
             * Admin Boundary Id
             * @description Optional link for village-level aggregation, not required for a catchment to exist on its own.
             */
            admin_boundary_id?: string | null;
        };
        /**
         * CatchmentDetailResponse
         * @description A single catchment, plus the geometry actually analysed.
         *
         *     Deliberately a subclass used only by `GET /catchments/{id}` rather
         *     than a field added to `CatchmentResponse` itself: the list endpoint
         *     shares that model and is fetched wholesale by the map, the Priority
         *     Queue and the compare view, so putting geometry on it would attach a
         *     polygon to every row of every list for the sake of one detail screen.
         *
         *     Exists so a report can draw the area it was actually computed over.
         *     Where an AOI was reshaped away from its village boundary, that shape
         *     lives only in `catchment.geometry` — the admin-boundary endpoints
         *     know nothing about it.
         */
        CatchmentDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Area Ha */
            area_ha: number;
            delineation_method: components["schemas"]["DelineationMethod"];
            /** Organization Id */
            organization_id: string | null;
            /** Admin Boundary Id */
            admin_boundary_id: string | null;
            /**
             * Resolution Flags
             * @description e.g. ["rainfall_sub_pixel", "et_sub_pixel", "high_relief_terrain"] — computed once at creation and reused by every downstream report (Blueprint v2 Part 4/Part 5).
             */
            resolution_flags: string[];
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
        };
        /**
         * CatchmentResponse
         * @description Mirrors `FarmResponse`'s exact convention: no raw geometry field
         *     in the basic response (geometry is fetched separately, e.g. for map
         *     rendering, by a later ticket's dedicated endpoint) — only scalar and
         *     list fields a client needs to display or reference a catchment by
         *     id.
         */
        CatchmentResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Area Ha */
            area_ha: number;
            delineation_method: components["schemas"]["DelineationMethod"];
            /** Organization Id */
            organization_id: string | null;
            /** Admin Boundary Id */
            admin_boundary_id: string | null;
            /**
             * Resolution Flags
             * @description e.g. ["rainfall_sub_pixel", "et_sub_pixel", "high_relief_terrain"] — computed once at creation and reused by every downstream report (Blueprint v2 Part 4/Part 5).
             */
            resolution_flags: string[];
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * DelineationMethod
         * @description How a catchment's boundary was obtained (Blueprint v2 Part 5).
         *
         *     AUTO_DEM is Phase 2 (D2) — reserved here now so the column that will use
         *     it doesn't need a later migration to add a value it was always going to
         *     need.
         * @enum {string}
         */
        DelineationMethod: "manual" | "upload" | "auto_dem";
        /** FactorScoreResponse */
        FactorScoreResponse: {
            factor: components["schemas"]["RiskFactor"];
            /** Value */
            value: number;
            band: components["schemas"]["RiskBand"];
            /** Raw Inputs */
            raw_inputs: {
                [key: string]: unknown;
            };
        };
        /**
         * FarmAssessmentHistoryResponse
         * @description Full assessment history for one farm, newest first, plus the
         *     in-flight run if any — the Farm detail timeline.
         */
        FarmAssessmentHistoryResponse: {
            /**
             * Farm Id
             * Format: uuid
             */
            farm_id: string;
            /** Items */
            items: components["schemas"]["AssessmentSummary"][];
            active_job: components["schemas"]["ActiveJobSummary"] | null;
        };
        /** FarmCreateRequest */
        FarmCreateRequest: {
            /**
             * Village Id
             * Format: uuid
             */
            village_id: string;
            geometry: components["schemas"]["GeoJSONPolygon"];
        };
        /** FarmListItem */
        FarmListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Village Id
             * Format: uuid
             */
            village_id: string;
            /** Village Name */
            village_name: string;
            /** Taluka Name */
            taluka_name: string;
            /** District Name */
            district_name: string;
            /** Area Ha */
            area_ha: number;
            /** Officer Name */
            officer_name: string;
            /**
             * Drawn By
             * Format: uuid
             */
            drawn_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            latest_assessment: components["schemas"]["AssessmentSummary"] | null;
            active_job: components["schemas"]["ActiveJobSummary"] | null;
        };
        /** FarmListResponse */
        FarmListResponse: {
            /** Items */
            items: components["schemas"]["FarmListItem"][];
            /** Total */
            total: number;
        };
        /** FarmResponse */
        FarmResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Village Id
             * Format: uuid
             */
            village_id: string;
            /** Area Ha */
            area_ha: number;
            /**
             * Drawn By
             * Format: uuid
             */
            drawn_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * GeoJSONMultiPolygon
         * @description A GeoJSON MultiPolygon — `Catchment.geometry`'s exact shape
         *     (`app/models/catchment.py`: MULTIPOLYGON, not POLYGON, "unlike a
         *     single farm field, a real watershed is not guaranteed to be simply
         *     connected"). A client submitting a single simply-connected boundary
         *     still uses this type, wrapped as a one-element MultiPolygon — valid,
         *     ordinary GeoJSON, not a special case this schema needs to detect.
         *
         *     Unlike `farm.py::GeoJSONPolygon`, holes (rings after the first, per
         *     polygon) are structurally permitted — a real watershed excluding an
         *     enclosed area is physically meaningful in a way a single farm
         *     field's boundary is not, so no "single ring only" restriction is
         *     imposed here.
         */
        GeoJSONMultiPolygon: {
            /**
             * Type
             * @constant
             */
            type: "MultiPolygon";
            /** Coordinates */
            coordinates: [
                number,
                number
            ][][][];
            /** Crs */
            crs?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * GeoJSONPolygon
         * @description A single-ring GeoJSON Polygon (no holes, no MultiPolygon) — a
         *     hand-drawn farm boundary is expected to be one simple, contiguous
         *     shape (Blueprint §01: manual polygon drawing is the deliberate MVP
         *     approach).
         */
        GeoJSONPolygon: {
            /**
             * Type
             * @constant
             */
            type: "Polygon";
            /** Coordinates */
            coordinates: [
                number,
                number
            ][][];
            /** Crs */
            crs?: {
                [key: string]: unknown;
            } | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobProgress */
        JobProgress: {
            /** Stages */
            stages: components["schemas"]["ProgressStage"][];
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "pending" | "running" | "done" | "failed";
        /** JobStatusResponse */
        JobStatusResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            type: components["schemas"]["JobType"];
            status: components["schemas"]["JobStatus"];
            /** Entity Id */
            entity_id: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            progress?: components["schemas"]["JobProgress"] | null;
        };
        /**
         * JobType
         * @enum {string}
         */
        JobType: "farm_report" | "portfolio_aggregation" | "catchment_water_report" | "catchment_boundary_upload";
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            role: components["schemas"]["UserRole"];
            /** Expires In */
            expires_in: number;
            /** Full Name */
            full_name: string;
        };
        /**
         * ObservationPoint
         * @description One monthly composited value from the satellite_observation cache —
         *     real persisted data from the generation run, never recomputed at read
         *     time (Blueprint §03: report reads never trigger a live GEE call).
         */
        ObservationPoint: {
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /** Value */
            value: number;
            /** Source Dates */
            source_dates?: string[];
        };
        /**
         * ProgressStage
         * @description One row of the honest execution timeline (M2B P8). Mirrors
         *     app/services/reporting/progress.py's stage shape exactly — that
         *     module is the only writer of this data.
         */
        ProgressStage: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "done" | "failed";
            /** Started At */
            started_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * RechargeStressScoreResponse
         * @description Field-for-field mirror of `app.models.water_balance.RechargeStressScore`
         *     — `weights_version_id` deliberately excluded: it is always `None`
         *     today (see `water_report_generator.py`'s own architecture-decision
         *     docstring, point 3 — no ConfigWeight row exists for this factor set
         *     yet), so exposing it would only ever show a client a field that
         *     never has a value.
         */
        RechargeStressScoreResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Stress Score */
            stress_score: number;
            stress_band: components["schemas"]["StressBand"];
            baseline_window: components["schemas"]["BaselineWindow"];
            /** Rainfall Anomaly Ratio */
            rainfall_anomaly_ratio: number | null;
            /** Vci */
            vci: number | null;
            /** Surface Water Trend */
            surface_water_trend: number | null;
            /** Cgwb Category */
            cgwb_category: string | null;
            /** Cgwb Category As Of */
            cgwb_category_as_of: string | null;
            /** Raw Inputs */
            raw_inputs: {
                [key: string]: unknown;
            };
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
        };
        /**
         * ReportAuditContext
         * @description REPORT V2 audit-appendix metadata not otherwise in the payload —
         *     real, derived from the completed Job's own stage timeline
         *     (app/services/reporting/progress.py), never a synthetic estimate. Both
         *     None for reports generated before this field existed, or if the
         *     originating Job row is no longer found.
         */
        ReportAuditContext: {
            /** Processing Started At */
            processing_started_at?: string | null;
            /** Processing Completed At */
            processing_completed_at?: string | null;
        };
        /**
         * ReportComparisonContext
         * @description REPORT V2 — the farm's own prior assessment, if one exists (real
         *     cross-assessment history via the append-only `risk_score` table, never
         *     a forecast). `has_previous_assessment=False` and all other fields None
         *     means this is the farm's first assessment — the honest answer, not an
         *     assumed baseline of zero.
         */
        ReportComparisonContext: {
            /**
             * Has Previous Assessment
             * @default false
             */
            has_previous_assessment: boolean;
            /** Previous Computed At */
            previous_computed_at?: string | null;
            /** Previous Overall Score */
            previous_overall_score?: number | null;
            /** Previous Factor Scores */
            previous_factor_scores?: {
                [key: string]: number;
            };
        };
        /**
         * ReportEvidenceContext
         * @description Answers 'which observations contributed' (M2B P9 Evidence tab).
         *     Both fields are the exact (start, end) _run_pipeline actually queried
         *     Earth Engine with — persisted at compute time (RiskScore.observation_
         *     window_start/end), never re-derived. None for reports computed before
         *     this column existed; the frontend shows the rest of the report
         *     normally and simply omits window-dependent Evidence detail.
         */
        ReportEvidenceContext: {
            /** Observation Window Start */
            observation_window_start: string | null;
            /** Observation Window End */
            observation_window_end: string | null;
            /** Expected Months */
            expected_months: number | null;
        };
        /**
         * ReportFarmContext
         * @description Farm identity block for the report header and map panel (Blueprint
         *     §08 "Farm information": provenance for anything entering a bank's
         *     file).
         */
        ReportFarmContext: {
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
            /** Village Name */
            village_name: string;
            /** Taluka Name */
            taluka_name: string;
            /** District Name */
            district_name: string;
            /** Officer Name */
            officer_name: string;
        };
        /** ReportGenerateRequest */
        ReportGenerateRequest: {
            /**
             * Lookback Years
             * @default 3
             */
            lookback_years: number;
        };
        /** ReportListItem */
        ReportListItem: {
            /**
             * Risk Score Id
             * Format: uuid
             */
            risk_score_id: string;
            /**
             * Farm Id
             * Format: uuid
             */
            farm_id: string;
            /** Village Name */
            village_name: string;
            /** Taluka Name */
            taluka_name: string;
            /** District Name */
            district_name: string;
            /** Area Ha */
            area_ha: number;
            /** Officer Name */
            officer_name: string;
            /** Overall Score */
            overall_score: number;
            overall_band: components["schemas"]["RiskBand"];
            /** Confidence */
            confidence: number;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Model Version */
            model_version: string;
        };
        /** ReportListResponse */
        ReportListResponse: {
            /** Items */
            items: components["schemas"]["ReportListItem"][];
            /** Total */
            total: number;
        };
        /**
         * ReportMethodContext
         * @description Answers 'why this score' (M2B P9 Method tab) — the versioned
         *     weights and floor rule actually applied, read back from config_weight
         *     via risk_score.weights_version_id. Never recomputed: RiskEngine.compute()
         *     is the only place factor-to-composite arithmetic happens; this is a
         *     read-only reflection of its already-persisted inputs and output.
         */
        ReportMethodContext: {
            /**
             * Weights Version Id
             * Format: uuid
             */
            weights_version_id: string;
            /** Weights */
            weights: {
                [key: string]: number;
            };
            /**
             * Weights Effective From
             * Format: date-time
             */
            weights_effective_from: string;
            /** Floor Threshold */
            floor_threshold: number;
            /** Weighted Average Score */
            weighted_average_score: number | null;
        };
        /** ReportResponse */
        ReportResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Farm Id
             * Format: uuid
             */
            farm_id: string;
            /** Farm Area Ha */
            farm_area_ha: number;
            /**
             * Village Id
             * Format: uuid
             */
            village_id: string;
            /** Overall Score */
            overall_score: number;
            overall_band: components["schemas"]["RiskBand"];
            /** Confidence */
            confidence: number;
            /** Model Version */
            model_version: string;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Factors */
            factors: components["schemas"]["FactorScoreResponse"][];
            farm: components["schemas"]["ReportFarmContext"];
            series: components["schemas"]["ReportSeries"];
            evidence: components["schemas"]["ReportEvidenceContext"];
            method: components["schemas"]["ReportMethodContext"];
            comparison?: components["schemas"]["ReportComparisonContext"];
            audit?: components["schemas"]["ReportAuditContext"];
        };
        /**
         * ReportSeries
         * @description The monthly series the dashboard charts (M2A P5). All four cached
         *     index types are included even though the M2A dashboard charts only
         *     NDVI and rainfall — MNDWI/NDMI back the M2B factor drill-downs with
         *     no further payload change. A month missing from a list was
         *     unobservable (cloud-blanked or not yet published), never zero.
         */
        ReportSeries: {
            /** Ndvi */
            ndvi: components["schemas"]["ObservationPoint"][];
            /** Mndwi */
            mndwi: components["schemas"]["ObservationPoint"][];
            /** Ndmi */
            ndmi: components["schemas"]["ObservationPoint"][];
            /** Rainfall */
            rainfall: components["schemas"]["ObservationPoint"][];
        };
        /** ReportTriggerResponse */
        ReportTriggerResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Status
             * @default queued
             */
            status: string;
        };
        /**
         * RiskBand
         * @enum {string}
         */
        RiskBand: "low" | "moderate" | "high" | "very_high";
        /**
         * RiskFactor
         * @enum {string}
         */
        RiskFactor: "vegetation_stability" | "water_availability" | "drought_risk" | "flood_exposure";
        /**
         * StorageChangeBand
         * @description The MVP headline figure for a water balance result (Blueprint v2 D5)
         *     — a qualitative, climatology-relative descriptor. The underlying mm
         *     value and its confidence interval are computed and stored, but shown
         *     only in the technical/detailed report view, never as the headline,
         *     because the mm figure is an unvalidated residual for every generic
         *     customer at MVP (calibration_status defaults to UNCALIBRATED).
         * @enum {string}
         */
        StorageChangeBand: "much_below_normal" | "below_normal" | "normal" | "above_normal" | "much_above_normal";
        /**
         * StressBand
         * @description Recharge-stress classification (Blueprint v2 Part 4) — mirrors
         *     RiskBand's exact vocabulary rather than inventing new terminology, since
         *     recharge-stress scoring reuses RiskEngine's percentile-rank statistical
         *     shape (Blueprint v2 D6).
         * @enum {string}
         */
        StressBand: "low" | "moderate" | "high" | "very_high";
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "credit_officer" | "branch_manager" | "risk_officer" | "ceo" | "chairman" | "programme_officer" | "programme_admin";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VillageCentroid */
        VillageCentroid: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /** VillageSearchResult */
        VillageSearchResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Taluka */
            taluka: string;
            /** District */
            district: string;
            centroid: components["schemas"]["VillageCentroid"];
        };
        /**
         * WaterBalanceResultResponse
         * @description Field-for-field mirror of `app.models.water_balance.WaterBalanceResult`
         *     (see that model for the full column-by-column rationale) — no
         *     catchment_id (redundant with the parent response's own field).
         */
        /**
         * One water year's water balance (June-May, not calendar year).
         * `months_covered` distinguishes a complete year from a partial
         * stub at the edge of the observation window.
         */
        AnnualWaterBalanceResponse: {
            /** Label */
            label: string;
            /** Start Year */
            start_year: number;
            /** Months Covered */
            months_covered: number;
            /** Rainfall Mm */
            rainfall_mm: number | null;
            /** Et Mm */
            et_mm: number | null;
            /** Runoff Mm */
            runoff_mm: number | null;
            /** Storage Change Mm */
            storage_change_mm: number | null;
        };
        WaterBalanceResultResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /** Rainfall Mm */
            rainfall_mm: number | null;
            /** Et Mm */
            et_mm: number | null;
            /** Runoff Mm */
            runoff_mm: number | null;
            /** Storage Change Mm */
            storage_change_mm: number | null;
            /**
             * Annual
             * @description Per water year, oldest first. Null on reports
             *     generated before this field existed — treat as "not
             *     computed", never as "no change".
             */
            annual?: components["schemas"]["AnnualWaterBalanceResponse"][] | null;
            storage_change_band: components["schemas"]["StorageChangeBand"];
            /** Data Completeness */
            data_completeness: number;
            calibration_status: components["schemas"]["CalibrationStatus"];
            /** Closed Catchment Assumed */
            closed_catchment_assumed: boolean;
            /** Resolution Flags */
            resolution_flags: string[];
            /** Model Version */
            model_version: string;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
        };
        /**
         * WaterReportDetailResponse
         * @description `GET /catchments/{id}/water-reports`' full response — the latest
         *     completed run's `WaterBalanceResult` + `RechargeStressScore`
         *     siblings, the `Job` that produced them, and a single `generated_at`
         *     timestamp: the shared `computed_at` both result rows are stamped
         *     with in the same orchestrator run (`water_report_generator.py`
         *     computes it once and passes it to both), not a third, independently
         *     meaningful value.
         */
        WaterReportDetailResponse: {
            /**
             * Catchment Id
             * Format: uuid
             */
            catchment_id: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            water_balance: components["schemas"]["WaterBalanceResultResponse"];
            recharge_stress: components["schemas"]["RechargeStressScoreResponse"];
            job: components["schemas"]["JobStatusResponse"];
        };
        /**
         * WaterReportHistoryItem
         * @description One past completed run for a catchment — the same
         *     `WaterBalanceResult` + `RechargeStressScore` sibling pair
         *     `WaterReportDetailResponse` carries for the latest run, without the
         *     `job` field (a history list has no use for re-fetching job/progress
         *     metadata for runs that finished long ago). Powers both the
         *     per-catchment trend view and multi-catchment comparison
         *     (docs/WELL_Labs_Raichur_Founder_Review_2026.md Part 4/5) — one shape,
         *     two frontend presentations, since both are just "several of these,
         *     read together" rather than distinct data needs.
         */
        WaterReportHistoryItem: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            water_balance: components["schemas"]["WaterBalanceResultResponse"];
            recharge_stress: components["schemas"]["RechargeStressScoreResponse"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    search_villages_api_v1_villages_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VillageSearchResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_farms_api_v1_farms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmListResponse"];
                };
            };
        };
    };
    create_farm_api_v1_farms_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FarmCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_farm_api_v1_farms__farm_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_farm_assessment_history_api_v1_farms__farm_id__assessments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmAssessmentHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assessments_api_v1_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentListResponse"];
                };
            };
        };
    };
    trigger_report_api_v1_farms__farm_id__reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportTriggerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_v1_reports__risk_score_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                risk_score_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reports_api_v1_reports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportListResponse"];
                };
            };
        };
    };
    get_report_pdf_api_v1_reports__risk_score_id__pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                risk_score_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_catchments_api_v1_catchments_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatchmentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_catchment_api_v1_catchments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatchmentCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatchmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_catchment_api_v1_catchments_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_catchment_api_v1_catchments_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatchmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_catchment_api_v1_catchments__catchment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                catchment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatchmentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_water_report_api_v1_catchments__catchment_id__water_reports_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                catchment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaterReportDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_water_report_api_v1_catchments__catchment_id__water_reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                catchment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportTriggerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_water_report_history_api_v1_catchments__catchment_id__water_reports_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                catchment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaterReportHistoryItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_admin_boundaries_api_v1_admin_boundaries_get: {
        parameters: {
            query?: {
                /** @description Omit to list top-level states. */
                parent_id?: string | null;
                /** @description Optional extra filter; children are already one level below parent_id. */
                level?: components["schemas"]["BoundaryLevel"] | null;
                /** @description Include each row's simplified geometry. Off by default so the cascading-dropdown case stays minimal; on, this is the only way to draw a village's neighbours in one request instead of one request per neighbour. */
                include_geometry?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminBoundarySummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_admin_boundary_api_v1_admin_boundaries__boundary_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                boundary_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminBoundaryDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
