/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/villages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Villages */
        get: operations["search_villages_api_v1_villages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/farms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Farms
         * @description The Farms workspace index (M2B P7 — Product Design v2 §7, screen 7):
         *     every farm the caller owns or shares a branch with, each carrying its
         *     latest assessment (if any) and its currently in-flight run (if any) so
         *     the list alone answers "what's the state of every farm I map." Two
         *     small batch queries instead of a join, matching this codebase's
         *     existing style (no window functions) and MVP-pilot data volume.
         */
        get: operations["list_farms_api_v1_farms_get"];
        put?: never;
        /**
         * Create Farm
         * @description Persist an officer-drawn farm boundary. Geometry validity,
         *     closedness, coordinate range, and non-zero area are already enforced
         *     by FarmCreateRequest at the request-parsing boundary (app/schemas/farm.py).
         */
        post: operations["create_farm_api_v1_farms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/farms/{farm_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Farm */
        get: operations["get_farm_api_v1_farms__farm_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/farms/{farm_id}/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Farm Assessment History
         * @description Every completed assessment for this farm, newest first, plus the
         *     in-flight run if any — the Farm detail timeline (Product Design v2
         *     §7.4). Same append-only RiskScore history the risk engine already
         *     guarantees (Blueprint §04/§07); this endpoint is a read-model over it,
         *     nothing new persisted.
         */
        get: operations["get_farm_assessment_history_api_v1_farms__farm_id__assessments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Assessments
         * @description The Assessments workspace index (M2B P7 — Product Design v2 §7,
         *     screen 5): every farm_report run the caller owns or shares a branch
         *     with, farm context resolved regardless of run status.
         *
         *     `entity_id` is polymorphic by design (P4 decision, report_generator.py):
         *     while a job is in flight or failed it holds the farm_id it was
         *     triggered for; once DONE it is overwritten with the resulting
         *     risk_score_id. Listing "every assessment with its farm" therefore means
         *     resolving both shapes and merging them — no schema change, just reading
         *     what's already there two different ways.
         */
        get: operations["list_assessments_api_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/farms/{farm_id}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Report */
        post: operations["trigger_report_api_v1_farms__farm_id__reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{risk_score_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_api_v1_reports__risk_score_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reports
         * @description The Reports workspace index (M2B P7 — Product Design v2 §7, screen
         *     9): every issued report the caller owns or shares a branch with,
         *     newest first — the auditor/manager entry point ("show me every report
         *     issued," not "show me every farm"). One joined query; RiskScore is
         *     append-only so this is simply every farm-scored row in scope, no
         *     latest-per-farm collapsing (that collapsing is what the Farms index is
         *     for — this index is intentionally the full issued-artifact ledger).
         */
        get: operations["list_reports_api_v1_reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{risk_score_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report Pdf
         * @description Blueprint §API: rendered PDF, cached after first render. A risk
         *     score row is immutable once computed, so the cache is keyed on
         *     (risk_score_id, layout version) and never expires — a layout change
         *     bumps PDF_LAYOUT_VERSION rather than invalidating files.
         */
        get: operations["get_report_pdf_api_v1_reports__risk_score_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveJobSummary */
        ActiveJobSummary: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            status: components["schemas"]["JobStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * AssessmentListItem
         * @description One farm-report run with its farm context resolved. Farm fields are
         *     nullable because a completed job's entity_id was overwritten with the
         *     risk-score id (P4 decision) — if that score's farm were ever deleted,
         *     the run row must still list rather than crash the index.
         */
        AssessmentListItem: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            status: components["schemas"]["JobStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Farm Id */
            farm_id: string | null;
            /** Village Name */
            village_name: string | null;
            /** Area Ha */
            area_ha: number | null;
            /** Officer Name */
            officer_name: string;
            /** Risk Score Id */
            risk_score_id: string | null;
            /** Overall Score */
            overall_score: number | null;
            overall_band: components["schemas"]["RiskBand"] | null;
            /** Error Message */
            error_message: string | null;
        };
        /** AssessmentListResponse */
        AssessmentListResponse: {
            /** Items */
            items: components["schemas"]["AssessmentListItem"][];
            /** Total */
            total: number;
        };
        /**
         * AssessmentSummary
         * @description The latest completed assessment for a farm — enough for a list row;
         *     the full report stays behind GET /reports/{id}.
         */
        AssessmentSummary: {
            /**
             * Risk Score Id
             * Format: uuid
             */
            risk_score_id: string;
            /** Overall Score */
            overall_score: number;
            overall_band: components["schemas"]["RiskBand"];
            /** Confidence */
            confidence: number;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Model Version */
            model_version: string;
        };
        /** FactorScoreResponse */
        FactorScoreResponse: {
            factor: components["schemas"]["RiskFactor"];
            /** Value */
            value: number;
            band: components["schemas"]["RiskBand"];
            /** Raw Inputs */
            raw_inputs: {
                [key: string]: unknown;
            };
        };
        /**
         * FarmAssessmentHistoryResponse
         * @description Full assessment history for one farm, newest first, plus the
         *     in-flight run if any — the Farm detail timeline.
         */
        FarmAssessmentHistoryResponse: {
            /**
             * Farm Id
             * Format: uuid
             */
            farm_id: string;
            /** Items */
            items: components["schemas"]["AssessmentSummary"][];
            active_job: components["schemas"]["ActiveJobSummary"] | null;
        };
        /** FarmCreateRequest */
        FarmCreateRequest: {
            /**
             * Village Id
             * Format: uuid
             */
            village_id: string;
            geometry: components["schemas"]["GeoJSONPolygon"];
        };
        /** FarmListItem */
        FarmListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Village Id
             * Format: uuid
             */
            village_id: string;
            /** Village Name */
            village_name: string;
            /** Taluka Name */
            taluka_name: string;
            /** District Name */
            district_name: string;
            /** Area Ha */
            area_ha: number;
            /** Officer Name */
            officer_name: string;
            /**
             * Drawn By
             * Format: uuid
             */
            drawn_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            latest_assessment: components["schemas"]["AssessmentSummary"] | null;
            active_job: components["schemas"]["ActiveJobSummary"] | null;
        };
        /** FarmListResponse */
        FarmListResponse: {
            /** Items */
            items: components["schemas"]["FarmListItem"][];
            /** Total */
            total: number;
        };
        /** FarmResponse */
        FarmResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Village Id
             * Format: uuid
             */
            village_id: string;
            /** Area Ha */
            area_ha: number;
            /**
             * Drawn By
             * Format: uuid
             */
            drawn_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * GeoJSONPolygon
         * @description A single-ring GeoJSON Polygon (no holes, no MultiPolygon) — a
         *     hand-drawn farm boundary is expected to be one simple, contiguous
         *     shape (Blueprint §01: manual polygon drawing is the deliberate MVP
         *     approach).
         */
        GeoJSONPolygon: {
            /**
             * Type
             * @constant
             */
            type: "Polygon";
            /** Coordinates */
            coordinates: [
                number,
                number
            ][][];
            /** Crs */
            crs?: {
                [key: string]: unknown;
            } | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobProgress */
        JobProgress: {
            /** Stages */
            stages: components["schemas"]["ProgressStage"][];
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "pending" | "running" | "done" | "failed";
        /** JobStatusResponse */
        JobStatusResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            type: components["schemas"]["JobType"];
            status: components["schemas"]["JobStatus"];
            /** Entity Id */
            entity_id: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            progress?: components["schemas"]["JobProgress"] | null;
        };
        /**
         * JobType
         * @enum {string}
         */
        JobType: "farm_report" | "portfolio_aggregation";
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            role: components["schemas"]["UserRole"];
            /** Expires In */
            expires_in: number;
            /** Full Name */
            full_name: string;
        };
        /**
         * ObservationPoint
         * @description One monthly composited value from the satellite_observation cache —
         *     real persisted data from the generation run, never recomputed at read
         *     time (Blueprint §03: report reads never trigger a live GEE call).
         */
        ObservationPoint: {
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /** Value */
            value: number;
            /** Source Dates */
            source_dates?: string[];
        };
        /**
         * ProgressStage
         * @description One row of the honest execution timeline (M2B P8). Mirrors
         *     app/services/reporting/progress.py's stage shape exactly — that
         *     module is the only writer of this data.
         */
        ProgressStage: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "done" | "failed";
            /** Started At */
            started_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ReportEvidenceContext
         * @description Answers 'which observations contributed' (M2B P9 Evidence tab).
         *     Both fields are the exact (start, end) _run_pipeline actually queried
         *     Earth Engine with — persisted at compute time (RiskScore.observation_
         *     window_start/end), never re-derived. None for reports computed before
         *     this column existed; the frontend shows the rest of the report
         *     normally and simply omits window-dependent Evidence detail.
         */
        ReportEvidenceContext: {
            /** Observation Window Start */
            observation_window_start: string | null;
            /** Observation Window End */
            observation_window_end: string | null;
            /** Expected Months */
            expected_months: number | null;
        };
        /**
         * ReportFarmContext
         * @description Farm identity block for the report header and map panel (Blueprint
         *     §08 "Farm information": provenance for anything entering a bank's
         *     file).
         */
        ReportFarmContext: {
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
            /** Village Name */
            village_name: string;
            /** Taluka Name */
            taluka_name: string;
            /** District Name */
            district_name: string;
            /** Officer Name */
            officer_name: string;
        };
        /** ReportGenerateRequest */
        ReportGenerateRequest: {
            /**
             * Lookback Years
             * @default 3
             */
            lookback_years: number;
        };
        /** ReportListItem */
        ReportListItem: {
            /**
             * Risk Score Id
             * Format: uuid
             */
            risk_score_id: string;
            /**
             * Farm Id
             * Format: uuid
             */
            farm_id: string;
            /** Village Name */
            village_name: string;
            /** Taluka Name */
            taluka_name: string;
            /** District Name */
            district_name: string;
            /** Area Ha */
            area_ha: number;
            /** Officer Name */
            officer_name: string;
            /** Overall Score */
            overall_score: number;
            overall_band: components["schemas"]["RiskBand"];
            /** Confidence */
            confidence: number;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Model Version */
            model_version: string;
        };
        /** ReportListResponse */
        ReportListResponse: {
            /** Items */
            items: components["schemas"]["ReportListItem"][];
            /** Total */
            total: number;
        };
        /**
         * ReportMethodContext
         * @description Answers 'why this score' (M2B P9 Method tab) — the versioned
         *     weights and floor rule actually applied, read back from config_weight
         *     via risk_score.weights_version_id. Never recomputed: RiskEngine.compute()
         *     is the only place factor-to-composite arithmetic happens; this is a
         *     read-only reflection of its already-persisted inputs and output.
         */
        ReportMethodContext: {
            /**
             * Weights Version Id
             * Format: uuid
             */
            weights_version_id: string;
            /** Weights */
            weights: {
                [key: string]: number;
            };
            /**
             * Weights Effective From
             * Format: date-time
             */
            weights_effective_from: string;
            /** Floor Threshold */
            floor_threshold: number;
            /** Weighted Average Score */
            weighted_average_score: number | null;
        };
        /** ReportResponse */
        ReportResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Farm Id
             * Format: uuid
             */
            farm_id: string;
            /** Farm Area Ha */
            farm_area_ha: number;
            /**
             * Village Id
             * Format: uuid
             */
            village_id: string;
            /** Overall Score */
            overall_score: number;
            overall_band: components["schemas"]["RiskBand"];
            /** Confidence */
            confidence: number;
            /** Model Version */
            model_version: string;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Factors */
            factors: components["schemas"]["FactorScoreResponse"][];
            farm: components["schemas"]["ReportFarmContext"];
            series: components["schemas"]["ReportSeries"];
            evidence: components["schemas"]["ReportEvidenceContext"];
            method: components["schemas"]["ReportMethodContext"];
        };
        /**
         * ReportSeries
         * @description The monthly series the dashboard charts (M2A P5). All four cached
         *     index types are included even though the M2A dashboard charts only
         *     NDVI and rainfall — MNDWI/NDMI back the M2B factor drill-downs with
         *     no further payload change. A month missing from a list was
         *     unobservable (cloud-blanked or not yet published), never zero.
         */
        ReportSeries: {
            /** Ndvi */
            ndvi: components["schemas"]["ObservationPoint"][];
            /** Mndwi */
            mndwi: components["schemas"]["ObservationPoint"][];
            /** Ndmi */
            ndmi: components["schemas"]["ObservationPoint"][];
            /** Rainfall */
            rainfall: components["schemas"]["ObservationPoint"][];
        };
        /** ReportTriggerResponse */
        ReportTriggerResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Status
             * @default queued
             */
            status: string;
        };
        /**
         * RiskBand
         * @enum {string}
         */
        RiskBand: "low" | "moderate" | "high" | "very_high";
        /**
         * RiskFactor
         * @enum {string}
         */
        RiskFactor: "vegetation_stability" | "water_availability" | "drought_risk" | "flood_exposure";
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "credit_officer" | "branch_manager" | "risk_officer" | "ceo" | "chairman";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VillageCentroid */
        VillageCentroid: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /** VillageSearchResult */
        VillageSearchResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Taluka */
            taluka: string;
            /** District */
            district: string;
            centroid: components["schemas"]["VillageCentroid"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_villages_api_v1_villages_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VillageSearchResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_farms_api_v1_farms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmListResponse"];
                };
            };
        };
    };
    create_farm_api_v1_farms_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FarmCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_farm_api_v1_farms__farm_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_farm_assessment_history_api_v1_farms__farm_id__assessments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmAssessmentHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assessments_api_v1_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentListResponse"];
                };
            };
        };
    };
    trigger_report_api_v1_farms__farm_id__reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportTriggerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_v1_reports__risk_score_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                risk_score_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reports_api_v1_reports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportListResponse"];
                };
            };
        };
    };
    get_report_pdf_api_v1_reports__risk_score_id__pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                risk_score_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
