"""Initial schema — full PostGIS schema per Engineering Blueprint v1 §04.

Creates every table from the blueprint's database design in one migration,
even though most stay empty until later milestones (M1/M3) populate them —
this is the M0 deliverable "stand up the schema... everything else depends
on it." Hand-written rather than autogenerated: no live database was
available in the environment this was authored in, so the migration is
built directly from the SQLAlchemy models and verified by offline DDL
compilation instead (see backend/tests/test_schema_ddl.py).

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-07-09
"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    boundary_level = postgresql.ENUM("state", "district", "taluka", "village", name="boundary_level")
    user_role = postgresql.ENUM(
        "credit_officer", "branch_manager", "risk_officer", "ceo", "chairman", name="user_role"
    )
    job_type = postgresql.ENUM("farm_report", "portfolio_aggregation", name="job_type")
    job_status = postgresql.ENUM("pending", "running", "done", "failed", name="job_status")
    satellite_index_type = postgresql.ENUM(
        "ndvi", "mndwi", "ndmi", "rainfall", "jrc_water_occurrence", name="satellite_index_type"
    )
    risk_band = postgresql.ENUM("low", "moderate", "high", "very_high", name="risk_band")
    risk_factor_band = postgresql.ENUM("low", "moderate", "high", "very_high", name="risk_factor_band")
    rollup_risk_band = postgresql.ENUM("low", "moderate", "high", "very_high", name="rollup_risk_band")
    risk_factor = postgresql.ENUM(
        "vegetation_stability", "water_availability", "drought_risk", "flood_exposure", name="risk_factor"
    )
    risk_entity_type = postgresql.ENUM("farm", "village", "branch", "district", name="risk_entity_type")
    observation_entity_type = postgresql.ENUM("farm", "village", "branch", "district", name="observation_entity_type")
    rollup_entity_type = postgresql.ENUM("farm", "village", "branch", "district", name="rollup_entity_type")

    # Every enum above is used on exactly one column each (deliberately named
    # per-table rather than shared) so create_table's default behavior of
    # auto-emitting CREATE TYPE for an inline enum column is sufficient —
    # calling .create() here too would double-emit CREATE TYPE and fail.

    op.create_table(
        "admin_boundary",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("level", boundary_level, nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("parent_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("admin_boundary.id"), nullable=True),
        sa.Column("lgd_code", sa.String(32), nullable=True),
        sa.Column("geometry", geoalchemy2.Geometry(geometry_type="MULTIPOLYGON", srid=4326), nullable=False),
        sa.Column(
            "geometry_simplified", geoalchemy2.Geometry(geometry_type="MULTIPOLYGON", srid=4326), nullable=True
        ),
        sa.UniqueConstraint("level", "name", "parent_id", name="uq_admin_boundary_level_name_parent"),
    )
    op.create_index("ix_admin_boundary_level", "admin_boundary", ["level"])
    op.create_index("ix_admin_boundary_name", "admin_boundary", ["name"])
    op.create_index("ix_admin_boundary_parent_id", "admin_boundary", ["parent_id"])

    op.create_table(
        "branch",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("district_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("admin_boundary.id"), nullable=True),
    )

    op.create_table(
        "village_branch_lookup",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("state", sa.String(255), nullable=False),
        sa.Column("district", sa.String(255), nullable=False),
        sa.Column("taluka", sa.String(255), nullable=False),
        sa.Column("village", sa.String(255), nullable=False),
        sa.Column("branch_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("branch.id"), nullable=False),
        sa.UniqueConstraint("state", "district", "taluka", "village", name="uq_village_branch_lookup_tuple"),
    )

    op.create_table(
        "app_user",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("email", sa.String(255), nullable=False, unique=True),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("full_name", sa.String(255), nullable=False),
        sa.Column("role", user_role, nullable=False),
        sa.Column("branch_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("branch.id"), nullable=True),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()),
    )
    op.create_index("ix_app_user_email", "app_user", ["email"], unique=True)

    op.create_table(
        "farm_polygon",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("village_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("admin_boundary.id"), nullable=False),
        sa.Column("geometry", geoalchemy2.Geometry(geometry_type="POLYGON", srid=4326), nullable=False),
        sa.Column("area_ha", sa.Numeric(10, 4), nullable=False),
        sa.Column("drawn_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("app_user.id"), nullable=False),
    )

    op.create_table(
        "farmer_identity",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("kcc_id", sa.String(64), nullable=True),
        sa.Column("contact", sa.String(64), nullable=True),
    )

    op.create_table(
        "loan",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column(
            "farmer_identity_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("farmer_identity.id"), nullable=False
        ),
        sa.Column("farm_polygon_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("farm_polygon.id"), nullable=True),
        sa.Column("branch_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("branch.id"), nullable=False),
        sa.Column("village_name", sa.String(255), nullable=False),
        sa.Column("crop", sa.String(128), nullable=False),
        sa.Column("outstanding_amount", sa.Numeric(14, 2), nullable=False),
    )

    op.create_table(
        "satellite_observation",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("entity_type", observation_entity_type, nullable=False),
        sa.Column("entity_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("index_type", satellite_index_type, nullable=False),
        sa.Column("period_start", sa.Date, nullable=False),
        sa.Column("period_end", sa.Date, nullable=False),
        sa.Column("value", sa.Float, nullable=False),
        sa.Column("source_dates", postgresql.JSONB, nullable=False, server_default="[]"),
    )
    op.create_index("ix_satellite_observation_entity_type", "satellite_observation", ["entity_type"])
    op.create_index("ix_satellite_observation_entity_id", "satellite_observation", ["entity_id"])

    op.create_table(
        "config_weight",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("weights", postgresql.JSONB, nullable=False),
        sa.Column("floor_thresholds", postgresql.JSONB, nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("app_user.id"), nullable=True),
    )

    op.create_table(
        "risk_score",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("entity_type", risk_entity_type, nullable=False),
        sa.Column("entity_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("overall_score", sa.Float, nullable=False),
        sa.Column("overall_band", risk_band, nullable=False),
        sa.Column("confidence", sa.Float, nullable=False),
        sa.Column("model_version", sa.String, nullable=False, server_default="rule-engine-v1"),
        sa.Column(
            "weights_version_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("config_weight.id"), nullable=False
        ),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_risk_score_entity_type", "risk_score", ["entity_type"])
    op.create_index("ix_risk_score_entity_id", "risk_score", ["entity_id"])

    op.create_table(
        "risk_factor_score",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("risk_score_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("risk_score.id"), nullable=False),
        sa.Column("factor", risk_factor, nullable=False),
        sa.Column("value", sa.Float, nullable=False),
        sa.Column("band", risk_factor_band, nullable=False),
        sa.Column("raw_inputs", postgresql.JSONB, nullable=False, server_default="{}"),
    )

    op.create_table(
        "risk_rollup",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("entity_type", rollup_entity_type, nullable=False),
        sa.Column("entity_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("exposure_amount", sa.Float, nullable=False),
        sa.Column("risk_band", rollup_risk_band, nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_risk_rollup_entity_type", "risk_rollup", ["entity_type"])
    op.create_index("ix_risk_rollup_entity_id", "risk_rollup", ["entity_id"])

    op.create_table(
        "job",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("type", job_type, nullable=False),
        sa.Column("status", job_status, nullable=False, server_default="pending"),
        sa.Column("entity_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("app_user.id"), nullable=False),
        sa.Column("error_message", sa.Text, nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )

    # No explicit spatial-index statements here: GeoAlchemy2's Geometry type
    # auto-creates a GIST index (named idx_<table>_<column>) for every
    # geometry column the moment op.create_table runs, via its own DDL
    # event listener. Adding explicit CREATE INDEX statements on top of that
    # (as an earlier version of this migration did) produced duplicate GIST
    # indexes on admin_boundary.geometry, admin_boundary.geometry_simplified,
    # and farm_polygon.geometry — verified and removed after running this
    # migration against a live PostGIS instance during M0 verification.


def downgrade() -> None:
    op.drop_table("job")
    op.drop_table("risk_rollup")
    op.drop_table("risk_factor_score")
    op.drop_table("risk_score")
    op.drop_table("config_weight")
    op.drop_table("satellite_observation")
    op.drop_table("loan")
    op.drop_table("farmer_identity")
    op.drop_table("farm_polygon")
    op.drop_table("app_user")
    op.drop_table("village_branch_lookup")
    op.drop_table("branch")
    op.drop_table("admin_boundary")

    bind = op.get_bind()
    for enum_name in (
        "rollup_entity_type",
        "observation_entity_type",
        "risk_entity_type",
        "risk_factor",
        "rollup_risk_band",
        "risk_factor_band",
        "risk_band",
        "satellite_index_type",
        "job_status",
        "job_type",
        "user_role",
        "boundary_level",
    ):
        postgresql.ENUM(name=enum_name).drop(bind, checkfirst=True)
